#+LATEX_HEADER: \usepackage{parskip}
#+LATEX_HEADER: \linespread{1.4}
#+OPTIONS: num:nil toc:nil

* Data Collection

Data collection comprises of two possible methods. A simple method that doesn't
require being physically present in a lecture room, and a more involved method
that requires our physical presence. Both methods are designed to automate data
collection as much as possible, avoiding as much manual work as possible in
favour of a fixed upfront development cost.

** The First Method

The first method involves an online questionnaire with questions including where
a user would be ideally located in a given lecture room, and how much they value
sitting near a friend. Note that the former question can be done by providing an
image of a lecture room where the student selects their preferred seat by simply
clicking on it. The form can be distributed via a URL to students via a mailing
list and data is collected by the server hosting the form as each user completes
the form.

** The Second Method

The second method involves recording data from a live event of students entering
a lecture room. This process is outlined as follows.

Firstly we need to be present at the lecture room, as students enter the room we
hand them a slip of paper informing them to fill out the questionnaire at the
given URL when they sit down. We ask them to fill it out when they sit down so
they can recall information about their process in choosing a seat as clearly as
possible, for example, recalling how many other students they had to pass in a
row. We use the phrasing "when you sit down" as opposed to the phrasing "as soon
as you sit down" as the latter might make the student suspicious as to the
nature of the questionnaire and could influence their process. Each paper has a
unique ID printed on it which we enter into a running Python program as we hand
the paper to the student, this program logs the students entrance time.

Example of a slip of paper handed to a student:

| Please fill out form at URL when you sit down. |
| No personally identifiable info is collected.  |
| https://ourform.com/abmform       Your ID: 5   |

When a student visits the URL they enter their unique ID, then they proceed to
answer the remaining questions in the questionnaire. This may include their seat
row and column, or how well they know their neighbours. Once they have reached
the end of the form, and we believe the form should be short, they hit done.

It should be noted that the questions of the simple form can be easily appended
as additional questions to this second form.

The time at which a student enters their ID on the form, and this should be the
first thing on the form, will give an indication of how long it took them to
find a seat, since we also have the timestamp of when they entered.

The time taken for this second method depends on when we assume students will
begin entering the lecture room and the time at which the last student will have
entered by. We suggest arriving twenty minutes before the lecture since we
really don't want to miss the first student. Twenty minutes after the lecture
starts should be sufficient time for us to remain, since it is not vital for us
to record a few very late students at the expense of our time.
